#!/bin/bash
clear
figlet "VOLT_SSH_MANAGER" | lolcat
echo -e "\033[1;33mINICIANDO, INSTALADOR \033[0m"
sleep 2s
wget https://raw.githubusercontent.com/prjkt-nv404/voltssh_manager/main/script/install; chmod 777 ./install; ./install

